version: '3'
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:80"
    volumes:
    - ./web-app:/usr/share/nginx/html:rw
